version: "3.9"

services:
  core:
    build: ./core
    ports:
      - "3001:3001"
    restart: always
    environment:
      PORT: 3001
      FIREBASE_SECRET_KEY_PATH: /app/firebase.json
      WHATSAPP_SESSION_PATH: /app/whatsapp
      LOG_GROUP_ID: 120363043346036120@g.us
    volumes:
      - ./core/whatsapp:/app/config/whatsapp
      - ./core/firebase.json:/app/firebase.json
    dns:
      - 8.8.8.8

  app:
    build: ./app
    ports:
      - "3000:80"
    environment:
      API_BASE_URL: http://localhost
    restart: always
    dns:
      - 8.8.8.8

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - "core"
      - "app"
    environment:
      API_URL: 'http://core:3001'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    dns:
      - 8.8.8.8

